### ISSUE TITLE
Using shared memory for sending data form library to daemon 

### ISSUE THREAD

**Issue by Manojcv55** [GENIVI/dlt-daemon#189] opened 2019-11-13 17:01 UTC

**Comment by ssugiura** [comment] 2019-11-13 23:18
@Manojcv55 Could you add explanation to this issue raised? Especially I need to understand your use case. Moreover, please take a look at https://github.com/GENIVI/dlt-daemon/issues/90.

**Comment by mvaradaraj** [comment] 2019-11-18 07:28
Hi @ssugiura 
Currently we are using integrity OS. Where file operations are costlier. So we trying to find alternative IPC mechanism (shared memory) instead of creating pipe. 
is there a way for using shared memory as IPC mechanism (sending payload and header)?

**Comment by votrungchi** [comment] 2019-11-18 07:43
@mvaradaraj Currently, DLT does not support shared memory as IPC for sending payload and header (only for payload is supported). Refer to #90 for more information. 
BTW, Will the UNIX_SOCKET as IPC improve in your use case? Could you please give it a try? compile with -DDLT_IPC=UNIX_SOCKET.

**Comment by ssugiura** [comment] 2019-12-10 12:46
@Manojcv55 @mvaradaraj As reported by @votrungchi , currently we don't support shared memory as IPC and we don't have any plan to extend the feature.
Also, could you check if @votrungchi 's suggestion would work?

**Comment by ssugiura** [comment] 2020-01-08 07:05
@Manojcv55 @mvaradaraj Any update from your side?

**Comment by Manojcv55** [comment] 2020-01-09 17:32
@ssugiura  Yes @votrungchi  suggestions worked , but when applications using dlt comes first and then dlt-daaemon comes there is missing of logs . Could you please suggest anything on this issue

**Comment by ssugiura** [comment] 2020-01-15 08:26
@Manojcv55 Sorry for my late response. Could you give me the reproduction steps? Ideally, it should work, as library and daemon has their own internal buffer to store the logs when daemon/client is not available. If it reaches to the maximum size of each buffer, then it will rotate to overwrite old log messages.

**Comment by Manojcv55** [comment] 2020-02-27 09:17
@ssugiura how many sockets will create if i use socket dlt version ?

**Comment by ssugiura** [comment] 2020-03-02 00:16
@Manojcv55 It will create one socket per DLT user.
With FIFO daemon will create two pipes for logging and controlling:
![image](https://user-images.githubusercontent.com/39760799/75636933-5888c780-5c66-11ea-905a-ff074b7201cb.png)
On the other hand there is only one socket for unix socket:
![image](https://user-images.githubusercontent.com/39760799/75636928-4c9d0580-5c66-11ea-8b6f-64e2598b9c7e.png)

**Comment by Manojcv55** [comment] 2020-03-06 23:46
Hi
If I run dlt-dameon CPU percentage is high in socket version, did you face
same issue

**Comment by ssugiura** [comment] 2020-03-10 09:56
@ssugiura I've never seen that issue. Does dlt-daemon internal log tells you anything? Sharing us the log itself would be very helpful.

**Comment by ssugiura** [comment] 2020-05-18 07:55
@Manojcv55 Any update on this? Having dlt-daemon internal logs will help us to proceed.

**Comment by ssugiura** [comment] 2020-07-06 01:23
Closing the issue since there's no update for long time. @Manojcv55 @mvaradaraj Please reopen this issue if the issue is not solved and you need any help from us. As written in previous comment, dlt-daemon internal logs would help us to understand the behavior. Thank you!

**Closed by ssugiura** 2020-07-06 01:23 UTC
