### ISSUE TITLE
Dlt log multiple file creation error.

### ISSUE THREAD

**Issue by kliu5** [GENIVI/dlt-daemon#94] opened 2019-01-16 05:27 UTC
Environment:
dlt daemon 2.18

dlt_logstorage.conf:
[FILTER1]
LogAppName=CM,PA,VM,VS,AUD,VIP
ContextName=.*
LogLevel=DLT_LOG_DEBUG
File=TJXW2000
FileSize=500000
NOFiles=2
SyncBehavior=ON_MSG

Steps:
Start dlt-daemon for a long time.

Expected:
Dlt-daemon only creates 2 files (as specified in dlt_logstorage.conf) and rotates them.

Error:
Dlt-daemon creates so many files, as shown below:
root@kliu5:/logs/dlt/log# ls -l
total 2414
-rw-rw-rw- 1 root socket 499947 Jan  1  2014 TJXW2000_1_19700101-000030.dlt
-rw-rw-rw- 1 root socket      0 Jan  1  2014 TJXW2000_2_20140101-001230.dlt
-rw-rw-rw- 1 root socket 499958 Jan  1  2014 TJXW2000_2_20140101-001231.dlt
-rw-rw-rw- 1 root socket  46059 Jan  1  2014 TJXW2000_3_20140101-001350.dlt
-rw-rw-rw- 1 root socket  17336 Jan  1  2014 TJXW2000_3_20140101-001351.dlt
-rw-rw-rw- 1 root socket    864 Jan  1  2014 TJXW2000_3_20140101-001352.dlt
-rw-rw-rw- 1 root socket 499990 Jan  1  2014 TJXW2000_3_20140101-001353.dlt
-rw-rw-rw- 1 root socket      0 Jan  1  2014 TJXW2000_4_20140101-000049.dlt
-rw-rw-rw- 1 root socket      0 Jan  1  2014 TJXW2000_4_20140101-000050.dlt
-rw-rw-rw- 1 root socket      0 Jan  1  2014 TJXW2000_4_20140101-000051.dlt
-rw-rw-rw- 1 root socket   4096 Jan  1  2014 TJXW2000_4_20140101-000054.dlt
-rw-rw-rw- 1 root socket 499965 Jan  1  2014 TJXW2000_4_20140101-000055.dlt
-rw-rw-rw- 1 root socket 122880 Jan  1  2014 TJXW2000_5_20140101-000204.dlt
-rw-rw-rw- 1 root socket  62317 Jan  1  2014 TJXW2000_5_20140101-000205.dlt
-rw-rw-rw- 1 root socket   4096 Jan  1  2014 TJXW2000_5_20140101-000207.dlt
-rw-rw-rw- 1 root socket   8192 Jan  1  2014 TJXW2000_5_20140101-000208.dlt
-rw-rw-rw- 1 root socket 103333 Jan  1  2014 TJXW2000_5_20140101-000209.dlt
-rw-rw-rw- 1 root socket  11196 Jan  1  2014 TJXW2000_5_20140101-000212.dlt
-rwxr-xr-x 1 root root      797 Jan  1  1970 dlt_logstorage.conf

I don't know why would this happen, and please help to check this problem, thanks!

**Comment by ManikandanChockalingam** [comment] 2019-01-16 09:39
Same as #85 . We havent fixed it in 2.18. we are working on the issue and soon will create a PR with the fix.

**Comment by ssugiura** [comment] 2019-03-25 02:50
We verified the issue is fixed with commit b7124c33826a53a1a66d3c6b7230ebd33735ab4a by the steps you have.

**Closed by ssugiura** 2019-03-25 02:50 UTC
